{% set name = "django-phonenumber-field" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_phonenumber_field-{{ version }}.tar.gz
  sha256: f19450625574ad3a2de047c409527d0e57699496849e71e53b53e8679ff67b27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2

test:
  imports:
    - phonenumber_field
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stefanfoulis/django-phonenumber-field
  doc_url: https://django-phonenumber-field.readthedocs.io/
  summary: An international phone number field for django models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
